# project name
BIN_NAME = cortexM_startup_code
MCU = LPC824
BOARD = 
C_SOURCES = 
CPP_SOURCES = src/startup.cpp src/main.cpp
S_SOURCES = 
INCLUDES = -Iinc
LIBDIR = 
LIBS = 
RLIBDIR = 
DEFINES = 
COMPILE_CXX_FLAGS =
COMPILE_CPP_FLAGS =
COMPILE_ASM_FLAGS =
LINK_FLAGS =